"""corporate actions and adjustment factors

Revision ID: cdcd9ee2ce69
Revises: a357ef3e5fdb
Created: 2026-08-11 05:01:46.016139+00:00

Replaces ``ohlcv.is_adjusted BOOLEAN`` with two derived factors, and adds the
``corporate_action`` table they are derived from. See
``SPRINT02_TECHNICAL_SPEC.md §4`` for why a boolean could not work: it records
*that* a bar was adjusted, not *by how much*, so the second corporate action has
nothing to build on and adjusting in place compounds silently.

``ADD COLUMN`` on a compressed hypertable was verified against TimescaleDB
2.17.2 before writing this — it is accepted; adding a FOREIGN KEY to one is not,
which is why ``corporate_action`` is a separate table rather than columns here.

**Downgrade loses adjustment state, not price data.** Raw OHLC is untouched
throughout, so nothing irreplaceable is destroyed — but the recorded actions go
with the table, and re-upgrading leaves every factor at 1.0 until the actions
are re-fetched and ``recompute_factors`` is run.

Checklist before merging this migration (EPIC01_TECHNICAL_SPEC.md §12):

- [x] ``downgrade()`` is implemented and actually tested, not left as ``pass``.
      ``upgrade head`` -> ``downgrade base`` -> ``upgrade head`` verified clean
      on a fresh database, 11 Aug 2026, with all 12 enum CHECK constraints and
      both ``_ts_idx`` hypertable indexes intact afterwards.
- [x] No TimescaleDB policy is added here, so there is no policy/hypertable
      drop ordering to get wrong.
- [x] No unique index is added on a hypertable. ``uq_action`` is on
      ``corporate_action``, which is an ordinary table.
- [x] ``dividend_amount`` is ``NUMERIC(14,4)`` (the shared ``Money`` type).
      The adjustment factors are ``NUMERIC(18,10)`` deliberately — they are
      ratios that multiply, not money, and four places would drift the earliest
      prices measurably across several actions.
- [x] ``announced_at`` and ``fetched_at`` are ``TIMESTAMP(timezone=True)``.
      ``ex_date`` is a ``DATE``: an ex-date is a calendar day on the exchange,
      not an instant, and giving it a timezone would invent precision.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cdcd9ee2ce69"
down_revision: str | None = "a357ef3e5fdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "SPLIT",
                "BONUS",
                "DIVIDEND",
                "RIGHTS",
                "CONSOLIDATION",
                name="corporate_action_type_enum",
                native_enum=False,
                create_constraint=True,
                length=29,
            ),
            nullable=False,
        ),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("ratio_from", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ratio_to", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("dividend_amount", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("announced_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action_type IN ('SPLIT', 'BONUS', 'CONSOLIDATION')  AND ratio_from IS NOT NULL AND ratio_to IS NOT NULL) OR (action_type = 'DIVIDEND' AND dividend_amount IS NOT NULL) OR action_type = 'RIGHTS'",
            name=op.f("ck_corporate_action_action_has_its_operands"),
        ),
        sa.CheckConstraint(
            "dividend_amount IS NULL OR dividend_amount > 0",
            name=op.f("ck_corporate_action_dividend_positive"),
        ),
        sa.CheckConstraint(
            "ratio_from IS NULL OR ratio_from > 0",
            name=op.f("ck_corporate_action_ratio_from_positive"),
        ),
        sa.CheckConstraint(
            "ratio_to IS NULL OR ratio_to > 0", name=op.f("ck_corporate_action_ratio_to_positive")
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["instruments.id"],
            name=op.f("fk_corporate_action_symbol_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_action")),
        sa.UniqueConstraint("symbol_id", "action_type", "ex_date", name="uq_action"),
    )
    op.create_index(
        "ix_action_symbol_date", "corporate_action", ["symbol_id", "ex_date"], unique=False
    )
    op.add_column(
        "instrument_daily_status", sa.Column("gsm_stage", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "instrument_daily_status",
        sa.Column(
            "asm_category",
            sa.Enum(
                "SHORT_TERM",
                "LONG_TERM",
                name="asm_category_enum",
                native_enum=False,
                create_constraint=True,
                length=26,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "ohlcv",
        sa.Column(
            "price_adj_factor",
            sa.Numeric(precision=18, scale=10),
            server_default="1.0",
            nullable=False,
        ),
    )
    op.add_column(
        "ohlcv",
        sa.Column(
            "volume_adj_factor",
            sa.Numeric(precision=18, scale=10),
            server_default="1.0",
            nullable=False,
        ),
    )
    op.drop_column("ohlcv", "is_adjusted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ohlcv",
        sa.Column(
            "is_adjusted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("ohlcv", "volume_adj_factor")
    op.drop_column("ohlcv", "price_adj_factor")
    op.drop_column("instrument_daily_status", "asm_category")
    op.drop_column("instrument_daily_status", "gsm_stage")
    op.drop_index("ix_action_symbol_date", table_name="corporate_action")
    op.drop_table("corporate_action")
    # ### end Alembic commands ###
