"""core schema

Revision ID: 15bc5004e435
Revises:
Created: 2026-08-07 06:55:09.937487+00:00

Checklist before merging this migration (EPIC01_TECHNICAL_SPEC.md §12):

- [ ] ``downgrade()`` is implemented and actually tested, not left as ``pass``.
      ``alembic upgrade head`` -> ``downgrade base`` -> ``upgrade head`` must
      run clean on an empty database.  This is an E01-S01 acceptance criterion
      and it is easy to leave broken.
- [ ] If this adds a TimescaleDB policy, ``downgrade()`` drops the policy
      BEFORE dropping the hypertable, or it fails.
- [ ] Any unique index on a hypertable includes the partitioning column
      (``ts``), which TimescaleDB requires.
- [ ] Money columns are ``NUMERIC(14,4)``, never float.
- [ ] Timestamps are ``TIMESTAMP(timezone=True)``, never naive.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "15bc5004e435"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("generated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("locked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("config_hash", sa.String(length=32), nullable=False),
        sa.Column("market_thesis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("macro_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_used", sa.String(length=64), nullable=True),
        sa.Column("ai_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_plan")),
        sa.UniqueConstraint("trade_date", name=op.f("uq_daily_plan_trade_date")),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tradingsymbol", sa.String(length=64), nullable=False),
        sa.Column(
            "exchange",
            sa.Enum(
                "NSE",
                "BSE",
                name="exchange_enum",
                native_enum=False,
                create_constraint=True,
                length=19,
            ),
            nullable=False,
        ),
        sa.Column("broker_token", sa.String(length=32), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("lot_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("first_seen", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("last_seen", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.CheckConstraint("lot_size >= 1", name=op.f("ck_instruments_lot_size_positive")),
        sa.CheckConstraint("tick_size > 0", name=op.f("ck_instruments_tick_size_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("exchange", "tradingsymbol", name="uq_instrument"),
    )
    op.create_index(
        "ix_instruments_sector",
        "instruments",
        ["sector"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index("ix_instruments_token", "instruments", ["broker_token"], unique=False)
    op.create_table(
        "strategy",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("dsl", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dsl_hash", sa.String(length=64), nullable=False),
        sa.Column("hypothesis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypothesis_frozen_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("applicable_regimes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("state_changed_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("retirement_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state <> 'ACTIVE' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)",
            name=op.f("ck_strategy_active_needs_approval"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["strategy.id"], name=op.f("fk_strategy_parent_id_strategy")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy")),
    )
    op.create_index(
        "ix_strategy_state",
        "strategy",
        ["state"],
        unique=False,
        postgresql_where=sa.text("state IN ('ACTIVE', 'DEGRADED', 'SHADOW', 'PAPER')"),
    )
    op.create_table(
        "strategy_trial",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "trial_ts",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_hash", sa.String(length=64), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("generation_batch_id", sa.UUID(), nullable=True),
        sa.Column("observed_sharpe", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("deflated_sharpe", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("pbo", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=12), nullable=False),
        sa.Column("failed_check", sa.String(length=8), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_trial")),
    )
    op.create_index("ix_trial_hash", "strategy_trial", ["strategy_hash"], unique=False)
    op.create_table(
        "decision_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "ts",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=28), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=12), nullable=False),
        sa.Column("reason_code", sa.String(length=48), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("service", sa.String(length=24), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_decision_log_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("ts", "seq", name=op.f("pk_decision_log")),
    )
    op.create_index("ix_audit_correlation", "decision_log", ["correlation_id", "ts"], unique=False)
    op.create_table(
        "instrument_daily_status",
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("is_t2t", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_asm", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_gsm", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_fno_ban", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_cas_stock", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("circuit_band_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("upper_circuit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("lower_circuit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("has_earnings_today", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("prev_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "fetched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["instruments.id"],
            name=op.f("fk_instrument_daily_status_symbol_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("symbol_id", "trade_date", name=op.f("pk_instrument_daily_status")),
    )
    op.create_index("ix_ids_date", "instrument_daily_status", ["trade_date"], unique=False)
    op.create_table(
        "ohlcv",
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "1m",
                "5m",
                "15m",
                "1h",
                "1d",
                "1w",
                name="timeframe_enum",
                native_enum=False,
                create_constraint=True,
                length=19,
            ),
            nullable=False,
        ),
        sa.Column("ts", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column("vwap", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("is_adjusted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "high >= low AND high >= open AND high >= close AND low <= open AND low <= close",
            name=op.f("ck_ohlcv_ohlc_coherent"),
        ),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0", name=op.f("ck_ohlcv_prices_positive")
        ),
        sa.CheckConstraint(
            "trade_count IS NULL OR trade_count >= 0",
            name=op.f("ck_ohlcv_trade_count_non_negative"),
        ),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_ohlcv_volume_non_negative")),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_ohlcv_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("symbol_id", "timeframe", "ts", name=op.f("pk_ohlcv")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("algo_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column(
            "side",
            sa.Enum(
                "BUY",
                "SELL",
                name="side_enum",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            sa.Enum(
                "LIMIT",
                "MARKET",
                "SL",
                "SLM",
                name="order_type_enum",
                native_enum=False,
                create_constraint=True,
                length=22,
            ),
            nullable=False,
        ),
        sa.Column(
            "product",
            sa.Enum(
                "MIS",
                "CNC",
                "NRML",
                name="product_enum",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("trigger_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("market_protection", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("filled_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("average_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "intent",
            sa.Enum(
                "ENTRY",
                "STOP",
                "TARGET",
                "SQUAREOFF",
                name="order_intent_enum",
                native_enum=False,
                create_constraint=True,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("placed_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_update_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("filled_quantity <= quantity", name=op.f("ck_orders_fill_not_over")),
        sa.CheckConstraint("filled_quantity >= 0", name=op.f("ck_orders_filled_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_orders_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name="uq_client_order"),
    )
    op.create_index("ix_orders_broker_id", "orders", ["broker_order_id"], unique=False)
    op.create_index("ix_orders_correlation", "orders", ["correlation_id"], unique=False)
    op.create_index(
        "ix_orders_open",
        "orders",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status NOT IN ('FILLED', 'CANCELLED', 'REJECTED')"),
    )
    op.create_table(
        "plan_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("tradeability_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "direction_bias",
            sa.Enum(
                "LONG",
                "SHORT",
                name="direction_enum",
                native_enum=False,
                create_constraint=True,
                length=21,
            ),
            nullable=False,
        ),
        sa.Column("ai_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("ai_rationale", sa.Text(), nullable=True),
        sa.Column("playbook", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gap_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)",
            name=op.f("ck_plan_candidate_confidence_in_range"),
        ),
        sa.CheckConstraint(
            "tradeability_score >= 0 AND tradeability_score <= 100",
            name=op.f("ck_plan_candidate_score_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["daily_plan.id"],
            name=op.f("fk_plan_candidate_plan_id_daily_plan"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_plan_candidate_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_candidate")),
        sa.UniqueConstraint("plan_id", "symbol_id", name="uq_plan_symbol"),
    )
    op.create_index("ix_candidate_plan_rank", "plan_candidate", ["plan_id", "rank"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "LONG",
                "SHORT",
                name="position_direction_enum",
                native_enum=False,
                create_constraint=True,
                length=21,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("stop_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("opened_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("squareoff_deadline", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSING",
                "CLOSED",
                name="position_status_enum",
                native_enum=False,
                create_constraint=True,
                length=23,
            ),
            nullable=False,
        ),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("exit_reason", sa.String(length=24), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("max_favourable_excursion", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("max_adverse_excursion", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND exit_price IS NOT NULL AND exit_reason IS NOT NULL)",
            name=op.f("ck_positions_closed_complete"),
        ),
        sa.CheckConstraint("entry_price > 0", name=op.f("ck_positions_entry_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_positions_quantity_positive")),
        sa.CheckConstraint("slot_index >= 0", name=op.f("ck_positions_slot_non_negative")),
        sa.CheckConstraint("stop_price > 0", name=op.f("ck_positions_stop_price_positive")),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_positions_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(
        "ix_positions_open",
        "positions",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status <> 'CLOSED'"),
    )
    op.create_index(
        "uq_open_slot",
        "positions",
        ["slot_index"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_index(
        "uq_open_symbol",
        "positions",
        ["symbol_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "shadow_signal",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("signalled_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "LONG",
                "SHORT",
                name="shadow_direction_enum",
                native_enum=False,
                create_constraint=True,
                length=21,
            ),
            nullable=False,
        ),
        sa.Column("price_at_signal", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("hypothetical_stop", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("hypothetical_outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategy.id"], name=op.f("fk_shadow_signal_strategy_id_strategy")
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["instruments.id"], name=op.f("fk_shadow_signal_symbol_id_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_signal")),
    )
    op.create_table(
        "strategy_performance",
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("trades", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("avg_r", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("realized_sharpe", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("vs_backtest_ratio", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategy.id"],
            name=op.f("fk_strategy_performance_strategy_id_strategy"),
        ),
        sa.PrimaryKeyConstraint("strategy_id", "as_of", name=op.f("pk_strategy_performance")),
    )
    op.create_table(
        "strategy_validation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("run_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_sharpe", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("deflated_sharpe", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("pbo", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("trial_count_at_run", sa.Integer(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("regimes_covered", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("holdout_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("equity_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategy.id"],
            name=op.f("fk_strategy_validation_strategy_id_strategy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_validation")),
    )
    op.create_table(
        "order_fills",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("fill_qty", sa.Integer(), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("filled_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "brokerage", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.Column("stt", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False),
        sa.Column(
            "exchange_charges",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("gst", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False),
        sa.Column(
            "sebi_charges", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "stamp_duty", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.CheckConstraint("fill_qty > 0", name=op.f("ck_order_fills_fill_qty_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_fills_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_fills")),
    )
    op.create_index("ix_fills_order", "order_fills", ["order_id"], unique=False)
    op.create_table(
        "trade_journal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("setup_type", sa.String(length=32), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column("market_regime", sa.String(length=20), nullable=False),
        sa.Column("ai_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("r_multiple", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("thesis_held", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_trade_journal_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_journal")),
    )
    op.create_index(
        "ix_journal_setup", "trade_journal", ["setup_type", "market_regime"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_journal_setup", table_name="trade_journal")
    op.drop_table("trade_journal")
    op.drop_index("ix_fills_order", table_name="order_fills")
    op.drop_table("order_fills")
    op.drop_table("strategy_validation")
    op.drop_table("strategy_performance")
    op.drop_table("shadow_signal")
    op.drop_index(
        "uq_open_symbol", table_name="positions", postgresql_where=sa.text("status = 'OPEN'")
    )
    op.drop_index(
        "uq_open_slot", table_name="positions", postgresql_where=sa.text("status = 'OPEN'")
    )
    op.drop_index(
        "ix_positions_open", table_name="positions", postgresql_where=sa.text("status <> 'CLOSED'")
    )
    op.drop_table("positions")
    op.drop_index("ix_candidate_plan_rank", table_name="plan_candidate")
    op.drop_table("plan_candidate")
    op.drop_index(
        "ix_orders_open",
        table_name="orders",
        postgresql_where=sa.text("status NOT IN ('FILLED', 'CANCELLED', 'REJECTED')"),
    )
    op.drop_index("ix_orders_correlation", table_name="orders")
    op.drop_index("ix_orders_broker_id", table_name="orders")
    op.drop_table("orders")
    op.drop_table("ohlcv")
    op.drop_index("ix_ids_date", table_name="instrument_daily_status")
    op.drop_table("instrument_daily_status")
    op.drop_index("ix_audit_correlation", table_name="decision_log")
    op.drop_table("decision_log")
    op.drop_index("ix_trial_hash", table_name="strategy_trial")
    op.drop_table("strategy_trial")
    op.drop_index(
        "ix_strategy_state",
        table_name="strategy",
        postgresql_where=sa.text("state IN ('ACTIVE', 'DEGRADED', 'SHADOW', 'PAPER')"),
    )
    op.drop_table("strategy")
    op.drop_index("ix_instruments_token", table_name="instruments")
    op.drop_index(
        "ix_instruments_sector", table_name="instruments", postgresql_where=sa.text("is_active")
    )
    op.drop_table("instruments")
    op.drop_table("daily_plan")
    # ### end Alembic commands ###
