"""Declarative base and the constraint naming convention.

This module exists so that Alembic's ``env.py`` has a stable
``target_metadata`` to import before any table has been written.  E01-S01
task 2 adds the actual models in ``models.py``; each one subclasses ``Base``
from here and is imported below so autogenerate can see it.

**The naming convention is the load-bearing part of this file.**  Without it,
PostgreSQL invents names for unnamed constraints and indexes, and those names
differ between the database Alembic autogenerated *from* and the one it later
runs *against*.  The symptom is a downgrade that fails with "constraint
... does not exist" on a database that visibly has the constraint — because it
is there under a server-generated name nobody recorded.  Setting the
convention up front means every constraint has a name the migration can
predict, which is also what makes ``downgrade base`` testable (an E01-S01
acceptance criterion).

Changing this convention later renames every constraint in the schema, so it
is set once, here, before the first migration.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.orm import DeclarativeBase

# `ix` index, `uq` unique, `ck` check, `fk` foreign key, `pk` primary key.
# Matches the convention already used by hand in EPIC01_TECHNICAL_SPEC.md §6
# (e.g. `uq_open_slot`, `ck_active_needs_approval`).
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(AsyncAttrs, DeclarativeBase):
    """Declarative base for every table in the system.

    ``AsyncAttrs`` is mixed in so that a lazy-loaded relationship can be
    awaited explicitly (``await obj.awaitable_attrs.some_relation``) rather
    than raising ``MissingGreenlet`` deep inside a service.  In an async
    codebase that error is otherwise the single most confusing thing the ORM
    does.
    """

    metadata = metadata


# ---------------------------------------------------------------------------
# Model imports for Alembic autogenerate.
#
# Autogenerate only sees tables that have been imported by the time env.py
# reads `Base.metadata`.  A model that is not imported here will be silently
# absent from the migration — and worse, an existing table with no
# corresponding import looks to Alembic like a table to DROP.
#
# E01-S01 task 2: add `from algotrader.common.db import models  # noqa: F401`
# below once models.py exists.
# ---------------------------------------------------------------------------
